version: '2'
services:
  cloudflare-ddns:
    image: oznu/cloudflare-ddns:latest
    restart: always
    environment:
      ENV_KEY_FILE: /etc/secrets/ddns.secret
      ZONE: benmcmahon.me
      SUBDOMAIN: home
